-- AI-CB PostgreSQL initialization script
-- This script is executed automatically on first container startup
-- when postgres_data volume is empty.
--
-- Responsibilities:
--   1. Enable database extensions required by the application
--   2. Create the six core application tables in pure SQL
--   3. Set database-wide defaults (timezone, etc.)
--
-- Compatibility notes:
--   - The app still ships SQLAlchemy models as a fallback / ORM source of truth.
--   - Legacy SQLite data should be migrated with backend/scripts/migrate_sqlite_to_postgres.py.

-- Common extensions for application features and future growth
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Set database-level timezone in a portable way (works even if DB name changes)
DO $$
DECLARE
	db_name text := current_database();
BEGIN
	EXECUTE format('ALTER DATABASE %I SET timezone TO %L', db_name, 'Asia/Taipei');
END
$$;

-- Ensure this init session also uses Taipei time immediately
SET TIME ZONE 'Asia/Taipei';

-- ---------------------------------------------------------------------------
-- Core application tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	hashed_password TEXT NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	is_admin BOOLEAN NOT NULL DEFAULT FALSE,
	role TEXT NOT NULL DEFAULT 'user'
		CHECK (role IN ('user', 'admin', 'moderator')),
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_login TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS conversations (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL
		REFERENCES users (id)
		ON DELETE CASCADE,
	title TEXT NOT NULL DEFAULT 'New Conversation',
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	conversation_id INTEGER NOT NULL
		REFERENCES conversations (id)
		ON DELETE CASCADE,
	content TEXT NOT NULL,
	is_user BOOLEAN NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	context_used TEXT,
	model_name TEXT
);

CREATE TABLE IF NOT EXISTS documents (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	filename TEXT NOT NULL,
	content TEXT NOT NULL,
	file_type TEXT NOT NULL,
	uploaded_by INTEGER
		REFERENCES users (id)
		ON DELETE SET NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_processed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS document_chunks (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	document_id INTEGER NOT NULL
		REFERENCES documents (id)
		ON DELETE CASCADE,
	content TEXT NOT NULL,
	chunk_index INTEGER NOT NULL,
	vector_id TEXT
);

CREATE TABLE IF NOT EXISTS custom_agents (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	role TEXT NOT NULL,
	expertise TEXT NOT NULL,
	prompt TEXT NOT NULL,
	tools JSON,
	is_public BOOLEAN NOT NULL DEFAULT TRUE,
	created_by INTEGER
		REFERENCES users (id)
		ON DELETE SET NULL
);

-- ---------------------------------------------------------------------------
-- Indexes for the app's actual query paths
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS ix_conversations_user_id ON conversations (user_id);
CREATE INDEX IF NOT EXISTS ix_messages_conversation_id ON messages (conversation_id);
CREATE INDEX IF NOT EXISTS ix_documents_uploaded_by ON documents (uploaded_by);
CREATE INDEX IF NOT EXISTS ix_document_chunks_document_id ON document_chunks (document_id);
CREATE INDEX IF NOT EXISTS ix_custom_agents_created_by ON custom_agents (created_by);
CREATE INDEX IF NOT EXISTS ix_custom_agents_name ON custom_agents (name);
CREATE INDEX IF NOT EXISTS ix_custom_agents_role ON custom_agents (role);

-- ---------------------------------------------------------------------------
-- Optional compatibility hooks
-- ---------------------------------------------------------------------------

-- If the ORM fallback runs after this script, it will simply detect the tables
-- already exist and keep using them without destructive changes.
